### ISSUE TITLE
Error happens when starting modding suite

### ISSUE THREAD

**Issue by RedNoul** [TK3600/moddingSuite#10]
I just downloaded modding suite and tried to do it but error blocks me.
it says

moddingSuite Error: 0 : Unhandeled exception occoured: System.UnauthorizedAccessException: Access to the path 'C:\$Recycle.Bin\S-1-5-18' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.EnumerateDirectories()
   at moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info) in F:\moddingSuite-master\moddingSuite\ViewModel\Edata\FileSystemOverviewViewModelBase.cs:line 41
   at moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info) in F:\moddingSuite-master\moddingSuite\ViewModel\Edata\FileSystemOverviewViewModelBase.cs:line 43
   at moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info) in F:\moddingSuite-master\moddingSuite\ViewModel\Edata\FileSystemOverviewViewModelBase.cs:line 43
   at moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseRoot() in F:\moddingSuite-master\moddingSuite\ViewModel\Edata\FileSystemOverviewViewModelBase.cs:line 34
   at moddingSuite.ViewModel.Edata.WorkspaceViewModel..ctor(Settings settings) in F:\moddingSuite-master\moddingSuite\ViewModel\Edata\WorkspaceViewModel.cs:line 21
   at moddingSuite.ViewModel.Edata.EdataManagerViewModel..ctor() in F:\moddingSuite-master\moddingSuite\ViewModel\Edata\EdataManagerViewModel.cs:line 79
   at moddingSuite.App.OnStartup(StartupEventArgs e) in F:\moddingSuite-master\moddingSuite\App.xaml.cs:line 68
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

or
moddingSuite.exe Error: 0 : Unhandeled exception occoured: System.UnauthorizedAccessException: 'C:\$Recycle.Bin\S-1-5-18' 경로에 대한 액세스가 거부되었습니다.
   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileSystemEnumerableIterator`1.CommonInit()
   위치: System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   위치: System.IO.DirectoryInfo.EnumerateDirectories()
   위치: moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info)
   위치: moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info)
   위치: moddingSuite.ViewModel.Edata.FileSystemOverviewViewModelBase.ParseDirectory(DirectoryInfo info)
   위치: moddingSuite.ViewModel.Edata.WorkspaceViewModel..ctor(Settings settings)
   위치: moddingSuite.ViewModel.Edata.EdataManagerViewModel..ctor()
   위치: moddingSuite.App.OnStartup(StartupEventArgs e)
   위치: System.Windows.Application.<.ctor>b__1_0(Object unused)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

is that happens because of BGM location? isn't it should be whith modding suite like this?
![dfbbnn](https://github.com/TK3600/moddingSuite/assets/154789539/a898e94c-be53-4c86-905e-bcb9c9c9b2e3)

i have any idea about access being denied.

**Comment by Rerosempire** [comment]
Not a modding suite bug. You probably didn't unzip the folder the modding suite came in, removed the exe from its original folder or tried to start the suite while WG was running.
